/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author User
 */
public class compras extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public compras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCmbLibro = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTxtCodCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCmbCliente = new javax.swing.JComboBox<>();
        jTxtPrecio = new javax.swing.JTextField();
        jTxtCantidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jbtnAgregar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jBtnEliminar1 = new javax.swing.JButton();
        jBtnFacturar = new javax.swing.JButton();
        jBtnNuevaFactura = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jTxtArticulos = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTxtTotalC = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaVenta = new javax.swing.JTable();
        jTxtISV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtSubtotal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTxtLibro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jCmbMetodoPago = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jTxtRecargo = new javax.swing.JTextField();
        jTxtStockMin = new javax.swing.JTextField();
        jTxtStockD = new javax.swing.JTextField();
        jTxtStockMax = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTxtCodCliente1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jBtnEliminar2 = new javax.swing.JButton();
        jBtnFacturar1 = new javax.swing.JButton();
        jBtnNuevaFactura1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jTxtArticulos1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTxtTotalC1 = new javax.swing.JTextField();
        jTxtTotal1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablaVenta1 = new javax.swing.JTable();
        jTxtCodCliente3 = new javax.swing.JTextField();
        jTxtCodCliente4 = new javax.swing.JTextField();
        jTxtCodCliente5 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTxtCodCliente6 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTxtCodCliente7 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTxtCodCliente9 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTxtCodCliente10 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTxtCodCliente11 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTxtCodCliente8 = new javax.swing.JTextField();
        jTxtCodCliente13 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jTxtCodCliente14 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ORDEN DE COMPRA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1140, 90);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "FORMULARIO DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel6.setLayout(null);

        jLabel10.setText("MÉTODO PAGO");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(480, 150, 110, 20);

        jTxtTotal.setEnabled(false);
        jPanel6.add(jTxtTotal);
        jTxtTotal.setBounds(860, 150, 170, 30);

        jLabel11.setText("CÓDIGO CLIENTE");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel6.add(jLabel11);
        jLabel11.setBounds(30, 60, 110, 20);

        jLabel12.setText("FECHA");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel6.add(jLabel12);
        jLabel12.setBounds(30, 20, 60, 20);

        jPanel6.add(jCmbLibro);
        jCmbLibro.setBounds(90, 110, 990, 30);

        jLabel13.setText("CLIENTE");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(380, 60, 60, 20);
        jPanel6.add(jTxtCodCliente);
        jTxtCodCliente.setBounds(140, 60, 230, 30);

        jLabel14.setText("PRECIO");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(30, 150, 70, 20);
        jPanel6.add(jSeparator1);
        jSeparator1.setBounds(30, 102, 1050, 10);

        jPanel6.add(jCmbCliente);
        jCmbCliente.setBounds(440, 60, 640, 30);

        jTxtPrecio.setEnabled(false);
        jPanel6.add(jTxtPrecio);
        jTxtPrecio.setBounds(90, 150, 150, 30);

        jTxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCantidadActionPerformed(evt);
            }
        });
        jTxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCantidadKeyTyped(evt);
            }
        });
        jPanel6.add(jTxtCantidad);
        jTxtCantidad.setBounds(320, 150, 150, 30);

        jLabel15.setText("CANTIDAD");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(250, 150, 80, 20);

        jbtnAgregar.setBorderPainted(false);
        jbtnAgregar.setContentAreaFilled(false);
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnAgregar);
        jbtnAgregar.setBounds(1040, 150, 40, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true));
        jPanel5.setLayout(null);

        jBtnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEliminar1.setText("ELIMINAR");
        jBtnEliminar1.setFocusPainted(false);
        jBtnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminar1ActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnEliminar1);
        jBtnEliminar1.setBounds(20, 110, 208, 40);

        jBtnFacturar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnFacturar.setText("FACTURAR");
        jBtnFacturar.setFocusPainted(false);
        jBtnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFacturarActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnFacturar);
        jBtnFacturar.setBounds(20, 60, 208, 40);

        jBtnNuevaFactura.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNuevaFactura.setText("NUEVA FACTURA");
        jBtnNuevaFactura.setFocusPainted(false);
        jBtnNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevaFacturaActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnNuevaFactura);
        jBtnNuevaFactura.setBounds(20, 10, 208, 40);

        jPanel6.add(jPanel5);
        jPanel5.setBounds(840, 190, 244, 160);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true));
        jPanel8.setLayout(null);

        jTxtArticulos.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtArticulos.setEnabled(false);
        jPanel8.add(jTxtArticulos);
        jTxtArticulos.setBounds(20, 30, 200, 30);

        jLabel18.setText("ARTÍCULOS");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(20, 10, 80, 20);

        jLabel19.setText("TOTAL COMPRA");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(20, 70, 170, 20);

        jTxtTotalC.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtTotalC.setEnabled(false);
        jPanel8.add(jTxtTotalC);
        jTxtTotalC.setBounds(20, 90, 200, 30);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(840, 360, 244, 130);

        jTablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "ID LIBRO", "LIBRO", "PRECIO", "CANTIDAD", "SUBTOTAL", "ISV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablaVenta);

        jPanel6.add(jScrollPane3);
        jScrollPane3.setBounds(20, 190, 810, 250);

        jTxtISV.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtISV.setEnabled(false);
        jPanel6.add(jTxtISV);
        jTxtISV.setBounds(470, 450, 140, 30);

        jLabel16.setText("ISV");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(440, 450, 50, 20);

        jLabel17.setText("SUBTOTAL");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(620, 450, 80, 20);

        jTxtSubtotal.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtSubtotal.setEnabled(false);
        jPanel6.add(jTxtSubtotal);
        jTxtSubtotal.setBounds(690, 450, 140, 30);

        jLabel20.setText("LIBRO");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel6.add(jLabel20);
        jLabel20.setBounds(30, 110, 60, 20);

        jTxtLibro.setEnabled(false);
        jPanel6.add(jTxtLibro);
        jTxtLibro.setBounds(960, 20, 120, 30);

        jLabel21.setText("TOTAL");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(810, 150, 60, 20);

        jCmbMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbMetodoPagoActionPerformed(evt);
            }
        });
        jPanel6.add(jCmbMetodoPago);
        jCmbMetodoPago.setBounds(580, 150, 210, 30);

        jLabel22.setText("RECARGO");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(210, 450, 80, 20);

        jTxtRecargo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtRecargo.setEnabled(false);
        jTxtRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRecargoActionPerformed(evt);
            }
        });
        jPanel6.add(jTxtRecargo);
        jTxtRecargo.setBounds(290, 450, 140, 30);

        jTxtStockMin.setEnabled(false);
        jPanel6.add(jTxtStockMin);
        jTxtStockMin.setBounds(700, 20, 120, 30);

        jTxtStockD.setEnabled(false);
        jPanel6.add(jTxtStockD);
        jTxtStockD.setBounds(830, 20, 120, 30);

        jTxtStockMax.setEnabled(false);
        jPanel6.add(jTxtStockMax);
        jTxtStockMax.setBounds(570, 20, 120, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 0, 0);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "FORMULARIO DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel7.setLayout(null);

        jLabel24.setText("PROVEEDOR");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel24);
        jLabel24.setBounds(10, 70, 110, 20);

        jLabel25.setText("FECHA ORDEN");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel25);
        jLabel25.setBounds(740, 20, 100, 20);

        jLabel26.setText("ARTICULO/SERVICIO");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(10, 250, 160, 20);
        jPanel7.add(jTxtCodCliente1);
        jTxtCodCliente1.setBounds(150, 240, 900, 30);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true));
        jPanel9.setLayout(null);

        jBtnEliminar2.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEliminar2.setText("ELIMINAR");
        jBtnEliminar2.setFocusPainted(false);
        jPanel9.add(jBtnEliminar2);
        jBtnEliminar2.setBounds(280, 10, 140, 40);

        jBtnFacturar1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnFacturar1.setText("ACEPTAR");
        jBtnFacturar1.setFocusPainted(false);
        jPanel9.add(jBtnFacturar1);
        jBtnFacturar1.setBounds(140, 10, 140, 40);

        jBtnNuevaFactura1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNuevaFactura1.setText("NUEVA COMPRA");
        jBtnNuevaFactura1.setFocusPainted(false);
        jPanel9.add(jBtnNuevaFactura1);
        jBtnNuevaFactura1.setBounds(10, 10, 130, 40);

        jPanel7.add(jPanel9);
        jPanel9.setBounds(400, 450, 430, 60);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true));
        jPanel10.setLayout(null);

        jTxtArticulos1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtArticulos1.setEnabled(false);
        jPanel10.add(jTxtArticulos1);
        jTxtArticulos1.setBounds(80, 20, 160, 30);

        jLabel29.setText("SUB TOTAL");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(10, 20, 80, 20);

        jLabel30.setText("ISV");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(10, 60, 50, 20);

        jTxtTotalC1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtTotalC1.setEnabled(false);
        jPanel10.add(jTxtTotalC1);
        jTxtTotalC1.setBounds(80, 60, 160, 30);

        jTxtTotal1.setEnabled(false);
        jPanel10.add(jTxtTotal1);
        jTxtTotal1.setBounds(80, 100, 160, 30);

        jLabel34.setText("TOTAL");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(10, 100, 60, 20);

        jPanel7.add(jPanel10);
        jPanel10.setBounds(864, 330, 250, 150);

        jTablaVenta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO", "DESCUENTO", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTablaVenta1);

        jPanel7.add(jScrollPane4);
        jScrollPane4.setBounds(20, 330, 810, 110);
        jPanel7.add(jTxtCodCliente3);
        jTxtCodCliente3.setBounds(850, 20, 230, 30);
        jPanel7.add(jTxtCodCliente4);
        jTxtCodCliente4.setBounds(150, 70, 570, 30);
        jPanel7.add(jTxtCodCliente5);
        jTxtCodCliente5.setBounds(150, 20, 130, 30);

        jLabel36.setText("NO. DE ORDEN");
        jLabel36.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel36);
        jLabel36.setBounds(10, 20, 110, 20);
        jPanel7.add(jTxtCodCliente6);
        jTxtCodCliente6.setBounds(150, 110, 930, 30);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel37.setText("DIRECCION DE ENTREGA");
        jLabel37.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel37);
        jLabel37.setBounds(10, 110, 210, 20);

        jLabel38.setText("ALMACEN");
        jLabel38.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel38);
        jLabel38.setBounds(10, 190, 110, 20);
        jPanel7.add(jTxtCodCliente7);
        jTxtCodCliente7.setBounds(150, 190, 570, 30);

        jLabel40.setText("PRECIO");
        jPanel7.add(jLabel40);
        jLabel40.setBounds(20, 290, 110, 20);
        jPanel7.add(jTxtCodCliente9);
        jTxtCodCliente9.setBounds(150, 280, 150, 30);

        jLabel41.setText("CANTIDAD");
        jPanel7.add(jLabel41);
        jLabel41.setBounds(330, 290, 110, 16);
        jPanel7.add(jTxtCodCliente10);
        jTxtCodCliente10.setBounds(410, 280, 90, 30);

        jLabel42.setText("DESCUENTO");
        jPanel7.add(jLabel42);
        jLabel42.setBounds(530, 290, 110, 20);
        jPanel7.add(jTxtCodCliente11);
        jTxtCodCliente11.setBounds(610, 280, 90, 30);

        jLabel39.setText("FECHA ENTREGA");
        jLabel39.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel39);
        jLabel39.setBounds(740, 70, 100, 20);
        jPanel7.add(jTxtCodCliente8);
        jTxtCodCliente8.setBounds(850, 70, 230, 30);
        jPanel7.add(jTxtCodCliente13);
        jTxtCodCliente13.setBounds(490, 150, 230, 30);

        jLabel44.setText("FECHA ORDEN");
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel44);
        jLabel44.setBounds(390, 150, 100, 20);

        jLabel45.setText("MODO DE PAGO");
        jLabel45.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(jLabel45);
        jLabel45.setBounds(10, 150, 110, 20);
        jPanel7.add(jTxtCodCliente14);
        jTxtCodCliente14.setBounds(150, 150, 220, 30);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 100, 1130, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCantidadActionPerformed

    }//GEN-LAST:event_jTxtCantidadActionPerformed

    private void jTxtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCantidadKeyPressed

    }//GEN-LAST:event_jTxtCantidadKeyPressed

    private void jTxtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCantidadKeyReleased
    /*    try {
            int cantidad = Integer.parseInt(jTxtCantidad.getText());
            int stockDisponible = Integer.parseInt(jTxtStockD.getText());
            int stockMin = Integer.parseInt(jTxtStockMin.getText());
            if (cantidad > stockDisponible) {
                JOptionPane.showMessageDialog(null, "No puede comprar esa cantidad de productos por stock insuficiente",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
                jTxtTotal.setText("0");
            } else {
                double precio = Double.parseDouble(jTxtPrecio.getText());
                double total = cantidad * precio;
                jTxtTotal.setText(Double.toString(total));
            }

        } catch (NumberFormatException ex) {
            System.err.println("Error al convertir el valor: " + ex.getMessage());
        }*/
    }//GEN-LAST:event_jTxtCantidadKeyReleased

    private void jTxtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCantidadKeyTyped

    }//GEN-LAST:event_jTxtCantidadKeyTyped

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed

    /*    int cantidad = Integer.parseInt(jTxtCantidad.getText());
        int stockDisponible = Integer.parseInt(jTxtStockD.getText());
        int stockMin = Integer.parseInt(jTxtStockMin.getText());
        String libro = (String) jCmbLibro.getSelectedItem();
        if ((stockDisponible - cantidad) < stockMin) {
            JOptionPane.showMessageDialog(null, "Ha llegado al límite del stock mínimo de " + libro + ". \nPronto se quedará sin stock suficiente. Reabastezca el inventario pronto.",
                "Stock Mínimo", JOptionPane.WARNING_MESSAGE);
        }

        tablaListaProductos();
        valoresTotales();
        bloquear();
        llenarCmbIdLibro();
        jBtnFacturar.setEnabled(true);
        jTxtPrecio.setText("0.0");
        jTxtCantidad.setText(null);
        jTxtTotal.setText("0.0");

        enumerarListaProductos();*/
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jBtnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminar1ActionPerformed
      /*  int selectedRow = jTablaVenta.getSelectedRow();

        if (selectedRow != -1) {
            eliminarLibro();
            DefaultTableModel model = (DefaultTableModel) jTablaVenta.getModel();
            model.removeRow(selectedRow);
            modelo.fireTableDataChanged();
        }

        enumerarListaProductos(); */

    }//GEN-LAST:event_jBtnEliminar1ActionPerformed

    private void jBtnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFacturarActionPerformed

      /*  int respuesta = JOptionPane.showConfirmDialog(
            null, "¿Está seguro de realizar la factuación? \nUna vez realizada, no podrá agregar más productos.",
            "Realizar factura", JOptionPane.YES_NO_OPTION
        );

        // Verificar la respuesta del usuario
        if (respuesta == JOptionPane.YES_OPTION) {
            factura();
            detalleFactura();
            idVenta = obtenerUltimoIdVentas();
            crearFacturaPDF();
            jBtnNuevaFactura.setEnabled(true);
            limpiar();

        }*/

    }//GEN-LAST:event_jBtnFacturarActionPerformed

    private void jBtnNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevaFacturaActionPerformed
    //    desbloquear();
    }//GEN-LAST:event_jBtnNuevaFacturaActionPerformed

    private void jCmbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbMetodoPagoActionPerformed
        /* jCmbMetodoPago.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selectedMethod = jCmbMetodoPago.getSelectedItem().toString();
                if (selectedMethod.equals("Tarjeta")) {
                    double recargo =
                    jTxtRecargo.setText("150");
                } else if (selectedMethod.equals("Efectivo")) {
                    jTxtRecargo.setText("0");
                }
            }
        });*/
    }//GEN-LAST:event_jCmbMetodoPagoActionPerformed

    private void jTxtRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRecargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRecargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEliminar1;
    private javax.swing.JButton jBtnEliminar2;
    private javax.swing.JButton jBtnFacturar;
    private javax.swing.JButton jBtnFacturar1;
    private javax.swing.JButton jBtnNuevaFactura;
    private javax.swing.JButton jBtnNuevaFactura1;
    private javax.swing.JComboBox<String> jCmbCliente;
    private javax.swing.JComboBox<String> jCmbLibro;
    private javax.swing.JComboBox<String> jCmbMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTablaVenta;
    private javax.swing.JTable jTablaVenta1;
    private javax.swing.JTextField jTxtArticulos;
    private javax.swing.JTextField jTxtArticulos1;
    private javax.swing.JTextField jTxtCantidad;
    private javax.swing.JTextField jTxtCodCliente;
    private javax.swing.JTextField jTxtCodCliente1;
    private javax.swing.JTextField jTxtCodCliente10;
    private javax.swing.JTextField jTxtCodCliente11;
    private javax.swing.JTextField jTxtCodCliente13;
    private javax.swing.JTextField jTxtCodCliente14;
    private javax.swing.JTextField jTxtCodCliente3;
    private javax.swing.JTextField jTxtCodCliente4;
    private javax.swing.JTextField jTxtCodCliente5;
    private javax.swing.JTextField jTxtCodCliente6;
    private javax.swing.JTextField jTxtCodCliente7;
    private javax.swing.JTextField jTxtCodCliente8;
    private javax.swing.JTextField jTxtCodCliente9;
    private javax.swing.JTextField jTxtISV;
    private javax.swing.JTextField jTxtLibro;
    private javax.swing.JTextField jTxtPrecio;
    private javax.swing.JTextField jTxtRecargo;
    private javax.swing.JTextField jTxtStockD;
    private javax.swing.JTextField jTxtStockMax;
    private javax.swing.JTextField jTxtStockMin;
    private javax.swing.JTextField jTxtSubtotal;
    private javax.swing.JTextField jTxtTotal;
    private javax.swing.JTextField jTxtTotal1;
    private javax.swing.JTextField jTxtTotalC;
    private javax.swing.JTextField jTxtTotalC1;
    private javax.swing.JButton jbtnAgregar;
    // End of variables declaration//GEN-END:variables
}
