/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import Conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class JInternalcategoria extends javax.swing.JInternalFrame {
Connection con=null;
ConexionBD conecta;
String sentenciaSQL;
ResultSet rs=null;
PreparedStatement ps=null;
DefaultTableModel modelo;
Object datoscategoria[]=new Object[3];
    /**
     * Creates new form JInternalcategoria
     */
    public JInternalcategoria() {
        initComponents();
    }
    
     public void conectarbd()
    {
        conecta=new ConexionBD("abarroteria");
        con=conecta.getConexion();
    }
    
    public void limpiar()
    {
        txtcodigo.setText("");
        txtnombre.setText("");
        txtdescripcion.setText("");
    }
    
     public void limpiarTabla()
    {
        modelo.setRowCount(0);
    } 
    
    public void crearcategoria() 
    {       
        try {

        conectarbd();
        sentenciaSQL="INSERT INTO categoria(id_categoria,nombre_categoria,descripcion,estado) VALUES(?,?,?,?)";
    
        ps=conecta.getConexion().prepareStatement(sentenciaSQL);
        ps.setInt(1,0);
        ps.setString(2,txtnombre.getText());
        ps.setString(3,txtdescripcion.getText());
        ps.setInt(4,1);
        ps.execute();
        
        JOptionPane.showMessageDialog(null,"DATOS INGRESADO CORRECTAMENTE");
        limpiar();
        con.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"ERROR"+ex.getMessage());
    }
    }
    
    public void leercategoria()
    {  
        try {
           conectarbd();
            sentenciaSQL="SELECT * FROM categoria WHERE estado=1";
            ps=con.prepareStatement(sentenciaSQL);
            rs=ps.executeQuery();
            modelo=(DefaultTableModel)Tldatos.getModel();
            while(rs.next())
            {
               datoscategoria[0]=(rs.getInt(1));
                datoscategoria[1]=(rs.getString(2));
                datoscategoria[2]=(rs.getString(3));
                modelo.addRow(datoscategoria);
            }
            Tldatos.setModel(modelo);
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"ERROR"+ex.getMessage());
            }       
    }  
    
     public void actualizarcategoria() 
    {
        try {
            conectarbd();
            sentenciaSQL="UPDATE categoria SET nombre_categoria=?,descripcion=? WHERE id_categoria=?";   
            ps=conecta.getConexion().prepareStatement(sentenciaSQL);
            ps.setString(1,txtnombre.getText());
            ps.setString(2,txtdescripcion.getText());
            ps.setString(3,txtcodigo.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null,"DATOS ACTUALIZADO CORRECTAMENTE");
            limpiar();
            con.close();
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"ERROR"+ex.getMessage());
            }
    }  
     
    public void eliminarcategoria() 
    {
        try {
            conectarbd();
            sentenciaSQL="UPDATE categoria SET estado=? WHERE id_categoria=?";   
            ps=conecta.getConexion().prepareStatement(sentenciaSQL);
            ps.setInt(1,2);
            ps.setString(2,txtcodigo.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null,"DATOS ACTUALIZADO CORRECTAMENTE");
            limpiar();
            con.close();
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,"ERROR"+ex.getMessage());
            }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tldatos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btncrear = new javax.swing.JButton();
        btnleer = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE CATEGORIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 633, 86);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Formulario de Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel2.setText("Codigo");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(28, 28, 42, 15);

        txtcodigo.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jPanel2.add(txtcodigo);
        txtcodigo.setBounds(20, 50, 90, 21);

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 80, 50, 15);

        txtnombre.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jPanel2.add(txtnombre);
        txtnombre.setBounds(20, 100, 90, 21);

        txtdescripcion.setColumns(20);
        txtdescripcion.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        txtdescripcion.setRows(5);
        jScrollPane1.setViewportView(txtdescripcion);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(140, 50, 140, 80);

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel4.setText("Descripcion");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(160, 30, 74, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 300, 170);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Tldatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "DESCRIPCION"
            }
        ));
        Tldatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TldatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tldatos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(300, 90, 292, 289);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(null);

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });
        jPanel3.add(btncrear);
        btncrear.setBounds(21, 14, 130, 23);

        btnleer.setText("Leer");
        btnleer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleerActionPerformed(evt);
            }
        });
        jPanel3.add(btnleer);
        btnleer.setBounds(20, 40, 130, 23);

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnmodificar);
        btnmodificar.setBounds(20, 70, 130, 23);

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnlimpiar);
        btnlimpiar.setBounds(160, 70, 130, 23);

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar);
        btneliminar.setBounds(160, 40, 130, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 260, 300, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TldatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TldatosMouseClicked
        // TODO add your handling code here:
        int fila=Tldatos.getSelectedRow();
        txtcodigo.setText(Tldatos.getValueAt(fila,0).toString());
        txtnombre.setText(Tldatos.getValueAt(fila,1).toString());
        txtdescripcion.setText(Tldatos.getValueAt(fila,2).toString());
    }//GEN-LAST:event_TldatosMouseClicked

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // TODO add your handling code here:
        if(!txtnombre.getText().isEmpty() && !txtdescripcion.getText().isEmpty())
        {
            crearcategoria();
        }else
        {
            JOptionPane.showMessageDialog(null,"COMPLETE TODOS LOS FORMULARIO");
        }

    }//GEN-LAST:event_btncrearActionPerformed

    private void btnleerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleerActionPerformed
        // TODO add your handling code here:
        leercategoria();
    }//GEN-LAST:event_btnleerActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        if(!txtnombre.getText().isEmpty() && !txtdescripcion.getText().isEmpty())
        {
            actualizarcategoria();
            limpiarTabla();
        }else
        {
            JOptionPane.showMessageDialog(null,"NO PUEDE DEJAR UN FORMULARIO VACIO");
        }

    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        if(!txtnombre.getText().isEmpty() && !txtdescripcion.getText().isEmpty())
        {
            eliminarcategoria();
            limpiarTabla();
        } else
        {
            JOptionPane.showMessageDialog(null,"ERROR");
        }

    }//GEN-LAST:event_btneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tldatos;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnleer;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
