/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Conexion.ConexionBD;
import static abarroteria.Menu_Principal.jDesktopPane1;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ventas1 extends javax.swing.JInternalFrame {

    String usuario, cod, sentenciaSQL;
    Connection con = null;
    ConexionBD connec;
    PreparedStatement ps = null;
    ResultSet rs = null;
    DefaultTableModel modelo;
    Object datosClientes[] = new Object[7];
    String nombreTabla = "CLIENTES";
    String codigo = "", nombre = "";

    /**
     * Creates new form ventas1
     */
    public ventas1() {
        initComponents();
        jTxtUsuario.setText(ClassPrin.usuario);
//        jCmbLibro.setEnabled(false);
//        llenarCmbCliente();
//        llenarCmbMetodoPago();
        jBtnFacturar.setEnabled(false);
//        jTxtLibro.setVisible(false);
//        jTxtStockMin.setVisible(false);
//        jTxtStockMax.setVisible(false);
//        jTxtStockD.setVisible(false);
        jdcFechaVenta.setEnabled(false);
        // Obtener la fecha actual
        Date fechaActual = new Date();
        // Asignar la fecha actual al componente JDateChooser
        jdcFechaVenta.setDate(fechaActual);
        jTxtUsuario.setText(ClassPrin.usuario);
    }

    public void buscar() {
        ConexionBD();
        String codigo = jTxtCodCliente1.getText().trim();

        if ("".equals(codigo) && "".equals(usuario)) {
            JOptionPane.showMessageDialog(null, "NO PUEDE DEJAR AMBOS CAMPOS VACÍOS PARA LA BÚSQUEDA, \n"
                    + "DEBE AL MENOS RELLENAR UN CAMPO.", "Error de búsqueda", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                if ("".equals(codigo)) {
                    codigo = "0";
                }

                sentenciaSQL = "SELECT * FROM clientes "
                        + "WHERE estado = 1 "
                        + "AND (id_cliente = ?) ";

                ps = con.prepareStatement(sentenciaSQL);
                ps.setInt(1, Integer.parseInt(codigo));

                rs = ps.executeQuery();

                String nombre;
                nombre = (rs.getString(1));

                int filas = modelo.getRowCount();
                if (filas < 1) {
                    JOptionPane.showMessageDialog(null, "NO SE ENCONTRÓ NINGÚN DATO QUE CONCORDASE");
                } else {
                    JOptionPane.showMessageDialog(null, "DATOS ENCONTRADOS CORRECTAMENTE.");
                }

                con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR NO SE PUDO LEER LOS DATOS DE LA TABLA.  " + ex.getMessage());
            }
        }
    }

    public void ConexionBD() {
        connec = new ConexionBD("abarroteria");
        con = connec.getConexion();
    }

    public void tablaListaProductos() {
        try {
            ConexionBD();
            DefaultTableModel modelo = (DefaultTableModel) jTablaVenta.getModel();
            String producto = jTxtNombreProducto.getText();
            sentenciaSQL = "SELECT precio_unitario FROM productos "
                    + "WHERE estado = 1 "
                    + "AND id_producto = " + jTxtCodProducto.getText().trim();
            ps = con.prepareStatement(sentenciaSQL);
            rs = ps.executeQuery();
            double precio = 0;
            if (rs.next()) {
                precio = (rs.getDouble("precio_unitario"));
            }

            int cantidad = Integer.parseInt(jTxtCantidad.getText());
            double subtotal = Double.parseDouble(jTxtCantidad.getText()) * precio;
            double isv = subtotal * 0.15;
            Object[] fila = new Object[]{jTxtCodProducto.getText(),
                 jTxtNombreProducto.getText(), precio, cantidad, subtotal, isv};
            modelo.addRow(fila);
            jTablaVenta.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(ventas1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jdcFechaVenta = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtCodCliente1 = new javax.swing.JTextField();
        jBtnBuscarCod = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlblImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaVenta = new javax.swing.JTable();
        jTxtISV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTxtRecargo = new javax.swing.JTextField();
        jTxtISV1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTxtISV2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jBtnEliminar1 = new javax.swing.JButton();
        jBtnFacturar1 = new javax.swing.JButton();
        jBtnNuevaFactura1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jBtnEliminar = new javax.swing.JButton();
        jBtnFacturar = new javax.swing.JButton();
        jBtnNuevaFactura = new javax.swing.JButton();
        jTxtUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnListaFacturas1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTxtCantidad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTxtCodProducto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTxtNombreProducto = new javax.swing.JTextField();
        jbtnListaFacturas2 = new javax.swing.JButton();
        jBtnBuscarCod1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 680));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 680));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel5.setLayout(null);
        jPanel5.add(jdcFechaVenta);
        jdcFechaVenta.setBounds(140, 40, 230, 30);

        jLabel12.setText("FECHA");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 40, 60, 20);

        jLabel11.setText("CÓDIGO");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 90, 110, 20);

        jTxtCliente.setEnabled(false);
        jPanel5.add(jTxtCliente);
        jTxtCliente.setBounds(120, 150, 230, 30);

        jLabel13.setText("CLIENTE");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 160, 90, 20);

        jTxtCodCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodCliente1ActionPerformed(evt);
            }
        });
        jTxtCodCliente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCodCliente1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtCodCliente1KeyReleased(evt);
            }
        });
        jPanel5.add(jTxtCodCliente1);
        jTxtCodCliente1.setBounds(120, 90, 230, 30);

        jBtnBuscarCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_24px.png"))); // NOI18N
        jBtnBuscarCod.setToolTipText("Presione para buscar un cliente por su número de identidad");
        jBtnBuscarCod.setBorderPainted(false);
        jBtnBuscarCod.setContentAreaFilled(false);
        jBtnBuscarCod.setFocusPainted(false);
        jBtnBuscarCod.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_32px.png"))); // NOI18N
        jBtnBuscarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarCodActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnBuscarCod);
        jBtnBuscarCod.setBounds(360, 90, 40, 32);

        jPanel2.setBackground(new java.awt.Color(237, 120, 74));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblImagen)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
            .addComponent(jlblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "DETALLE DE VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel4.setLayout(null);

        jTablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO", "SUBTOTAL", "ISV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablaVenta);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 30, 590, 380);

        jTxtISV.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtISV.setEnabled(false);
        jPanel4.add(jTxtISV);
        jTxtISV.setBounds(470, 540, 140, 30);

        jLabel16.setText("ISV");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(350, 460, 50, 20);

        jLabel17.setText("TOTAL");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(350, 550, 80, 20);

        jLabel22.setText("DESCUENTO");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(350, 420, 110, 20);

        jTxtRecargo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtRecargo.setEnabled(false);
        jTxtRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRecargoActionPerformed(evt);
            }
        });
        jPanel4.add(jTxtRecargo);
        jTxtRecargo.setBounds(470, 420, 140, 30);

        jTxtISV1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtISV1.setEnabled(false);
        jPanel4.add(jTxtISV1);
        jTxtISV1.setBounds(470, 460, 140, 30);

        jLabel18.setText("SUBTOTAL");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(350, 510, 80, 20);

        jTxtISV2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtISV2.setEnabled(false);
        jPanel4.add(jTxtISV2);
        jTxtISV2.setBounds(470, 500, 140, 30);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true));
        jPanel8.setLayout(null);

        jBtnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEliminar1.setText("ELIMINAR");
        jBtnEliminar1.setFocusPainted(false);
        jBtnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminar1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBtnEliminar1);
        jBtnEliminar1.setBounds(20, 110, 208, 40);

        jBtnFacturar1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnFacturar1.setText("FACTURAR");
        jBtnFacturar1.setFocusPainted(false);
        jBtnFacturar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFacturar1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBtnFacturar1);
        jBtnFacturar1.setBounds(20, 60, 208, 40);

        jBtnNuevaFactura1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNuevaFactura1.setText("NUEVA FACTURA");
        jBtnNuevaFactura1.setFocusPainted(false);
        jBtnNuevaFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevaFactura1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBtnNuevaFactura1);
        jBtnNuevaFactura1.setBounds(20, 10, 208, 40);

        jPanel4.add(jPanel8);
        jPanel8.setBounds(840, 190, 244, 160);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true));
        jPanel7.setLayout(null);

        jBtnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEliminar.setText("ELIMINAR");
        jBtnEliminar.setFocusPainted(false);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnEliminar);
        jBtnEliminar.setBounds(20, 110, 208, 40);

        jBtnFacturar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnFacturar.setText("FACTURAR");
        jBtnFacturar.setFocusPainted(false);
        jBtnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFacturarActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnFacturar);
        jBtnFacturar.setBounds(20, 60, 208, 40);

        jBtnNuevaFactura.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNuevaFactura.setText("NUEVA FACTURA");
        jBtnNuevaFactura.setFocusPainted(false);
        jBtnNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevaFacturaActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnNuevaFactura);
        jBtnNuevaFactura.setBounds(20, 10, 208, 40);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(50, 420, 260, 160);

        jTxtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTxtUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTxtUsuario.setForeground(new java.awt.Color(237, 120, 74));
        jTxtUsuario.setText("AQUÍ IRÁ EL USUARIO QUE ESTÁ INGRESANDO");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("USUARIO: ");

        jbtnListaFacturas1.setBackground(new java.awt.Color(237, 120, 74));
        jbtnListaFacturas1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnListaFacturas1.setText("VER FACTURAS");
        jbtnListaFacturas1.setToolTipText("");
        jbtnListaFacturas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListaFacturas1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel6.setLayout(null);

        jLabel19.setText("CÓDIGO");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel6.add(jLabel19);
        jLabel19.setBounds(20, 60, 110, 20);
        jPanel6.add(jTxtCantidad);
        jTxtCantidad.setBounds(140, 170, 230, 30);

        jLabel20.setText("CANTIDAD");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(20, 180, 90, 20);

        jTxtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtCodProductoKeyReleased(evt);
            }
        });
        jPanel6.add(jTxtCodProducto);
        jTxtCodProducto.setBounds(120, 60, 230, 30);

        jLabel21.setText("PRODUCTO");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(20, 110, 90, 20);

        jTxtNombreProducto.setEnabled(false);
        jPanel6.add(jTxtNombreProducto);
        jTxtNombreProducto.setBounds(140, 110, 230, 30);

        jbtnListaFacturas2.setBackground(new java.awt.Color(237, 120, 74));
        jbtnListaFacturas2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnListaFacturas2.setText("Agregar");
        jbtnListaFacturas2.setToolTipText("");
        jbtnListaFacturas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListaFacturas2ActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnListaFacturas2);
        jbtnListaFacturas2.setBounds(80, 230, 247, 36);

        jBtnBuscarCod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_24px.png"))); // NOI18N
        jBtnBuscarCod1.setToolTipText("Presione para buscar un cliente por su número de identidad");
        jBtnBuscarCod1.setBorderPainted(false);
        jBtnBuscarCod1.setContentAreaFilled(false);
        jBtnBuscarCod1.setFocusPainted(false);
        jBtnBuscarCod1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search_32px.png"))); // NOI18N
        jBtnBuscarCod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarCod1ActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnBuscarCod1);
        jBtnBuscarCod1.setBounds(360, 60, 40, 32);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(jbtnListaFacturas1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtUsuario)
                            .addComponent(jLabel6)))
                    .addComponent(jbtnListaFacturas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCodCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodCliente1ActionPerformed

    private void jTxtCodCliente1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodCliente1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            // Cuando se detecte la tecla "Tab", mover el foco al segundo campo de texto
            System.out.println("Hola");
            ConexionBD();
            sentenciaSQL = "select id_cliente,nombre_cliente from clientes where id_cliente=" + jTxtCodCliente1.getText().trim() + "and estado=1";
            try {
                ps = con.prepareStatement(sentenciaSQL);
                rs = ps.executeQuery();
                String nombre;
                int codigo;
                codigo = (rs.getInt(1));
                nombre = (rs.getString(2));
                con.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "No se encontro el cliente.  " + ex.getMessage());
            }
            jTxtCodProducto.requestFocus();
        }
    }//GEN-LAST:event_jTxtCodCliente1KeyReleased

    private void jBtnBuscarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarCodActionPerformed
        buscarClientes clientes = new buscarClientes();
        jDesktopPane1.add(clientes);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = clientes.getSize();
        clientes.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        clientes.show();
    }//GEN-LAST:event_jBtnBuscarCodActionPerformed

    private void jTxtRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRecargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRecargoActionPerformed

    private void jBtnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminar1ActionPerformed
        //        int selectedRow = jTablaVenta.getSelectedRow();
        //
        //        if (selectedRow != -1) {
        //            eliminarLibro();
        //            DefaultTableModel model = (DefaultTableModel) jTablaVenta.getModel();
        //            model.removeRow(selectedRow);
        //            modelo.fireTableDataChanged();
        //        }
        //
        //        enumerarListaProductos();
    }//GEN-LAST:event_jBtnEliminar1ActionPerformed

    private void jBtnFacturar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFacturar1ActionPerformed
        //
        //        int respuesta = JOptionPane.showConfirmDialog(
        //            null, "¿Está seguro de realizar la factuación? \nUna vez realizada, no podrá agregar más productos.",
        //            "Realizar factura", JOptionPane.YES_NO_OPTION
        //        );
        //
        //        // Verificar la respuesta del usuario
        //        if (respuesta == JOptionPane.YES_OPTION) {
        //            factura();
        //            detalleFactura();
        //            idVenta = obtenerUltimoIdVentas();
        //            crearFacturaPDF();
        //            jBtnNuevaFactura.setEnabled(true);
        //            limpiar();
        //
        //        }
    }//GEN-LAST:event_jBtnFacturar1ActionPerformed

    private void jBtnNuevaFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevaFactura1ActionPerformed
        //        desbloquear();
    }//GEN-LAST:event_jBtnNuevaFactura1ActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        //        int selectedRow = jTablaVenta.getSelectedRow();
        //
        //        if (selectedRow != -1) {
        //            eliminarLibro();
        //            DefaultTableModel model = (DefaultTableModel) jTablaVenta.getModel();
        //            model.removeRow(selectedRow);
        //            modelo.fireTableDataChanged();
        //        }
        //
        //        enumerarListaProductos();
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFacturarActionPerformed

        //        int respuesta = JOptionPane.showConfirmDialog(
        //            null, "¿Está seguro de realizar la factuación? \nUna vez realizada, no podrá agregar más productos.",
        //            "Realizar factura", JOptionPane.YES_NO_OPTION
        //        );
        //
        //        // Verificar la respuesta del usuario
        //        if (respuesta == JOptionPane.YES_OPTION) {
        //            factura();
        //            detalleFactura();
        //            idVenta = obtenerUltimoIdVentas();
        //            crearFacturaPDF();
        //            jBtnNuevaFactura.setEnabled(true);
        //            limpiar();
        //
        //        }
    }//GEN-LAST:event_jBtnFacturarActionPerformed

    private void jBtnNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevaFacturaActionPerformed
        //        desbloquear();
    }//GEN-LAST:event_jBtnNuevaFacturaActionPerformed

    private void jbtnListaFacturas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListaFacturas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnListaFacturas1ActionPerformed

    private void jTxtCodProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodProductoKeyReleased
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            // Cuando se detecte la tecla "Tab", mover el foco al segundo campo de texto
//            ConexionBD();
//            sentenciaSQL = "select id_producto,nombre_producto from productos where id_producto=" + jTxtCodProducto.getText().trim() + "and estado=1";
//            try {
//                ps = con.prepareStatement(sentenciaSQL);
//                rs = ps.executeQuery();
//                String nombre;
//                int codigo;
//                codigo = (rs.getInt(1));
//                nombre = (rs.getString(2));
//                con.close();
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(null, "No se encontro el producto.  " + ex.getMessage());
//            }
//            jTxtCantidad.requestFocus();
//        }
    }//GEN-LAST:event_jTxtCodProductoKeyReleased

    private void jbtnListaFacturas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListaFacturas2ActionPerformed
        int cantidad = Integer.parseInt(jTxtCantidad.getText());
        String producto = jTxtNombreProducto.getText();
//                if ((stockDisponible - cantidad) < stockMin) {
//                    JOptionPane.showMessageDialog(null, "Ha llegado al límite del stock mínimo de " + libro + ". \nPronto se quedará sin stock suficiente. Reabastezca el inventario pronto.",
//                            "Stock Mínimo", JOptionPane.WARNING_MESSAGE);
//                }

        tablaListaProductos();
//                valoresTotales();
//                bloquear();
//                llenarCmbIdLibro();
//                jBtnFacturar.setEnabled(true);
//                jTxtPrecio.setText("0.0");
//                jTxtCantidad.setText(null);
//                jTxtTotal.setText("0.0");
//        
//                enumerarListaProductos();
    }//GEN-LAST:event_jbtnListaFacturas2ActionPerformed

    private void jBtnBuscarCod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarCod1ActionPerformed
        buscarProducto productos = new buscarProducto();
        jDesktopPane1.add(productos);
        Dimension desktopSize = jDesktopPane1.getSize();
        Dimension FrameSize = productos.getSize();
        productos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        productos.show();
    }//GEN-LAST:event_jBtnBuscarCod1ActionPerformed

    private void jTxtCodCliente1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodCliente1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            System.out.println("Hola");
        }
        
    }//GEN-LAST:event_jTxtCodCliente1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarCod;
    private javax.swing.JButton jBtnBuscarCod1;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnEliminar1;
    private javax.swing.JButton jBtnFacturar;
    private javax.swing.JButton jBtnFacturar1;
    private javax.swing.JButton jBtnNuevaFactura;
    private javax.swing.JButton jBtnNuevaFactura1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablaVenta;
    private javax.swing.JTextField jTxtCantidad;
    protected static javax.swing.JTextField jTxtCliente;
    protected static javax.swing.JTextField jTxtCodCliente1;
    protected static javax.swing.JTextField jTxtCodProducto;
    private javax.swing.JTextField jTxtISV;
    private javax.swing.JTextField jTxtISV1;
    private javax.swing.JTextField jTxtISV2;
    protected static javax.swing.JTextField jTxtNombreProducto;
    private javax.swing.JTextField jTxtRecargo;
    private javax.swing.JLabel jTxtUsuario;
    private javax.swing.JButton jbtnListaFacturas1;
    private javax.swing.JButton jbtnListaFacturas2;
    private com.toedter.calendar.JDateChooser jdcFechaVenta;
    private javax.swing.JLabel jlblImagen;
    // End of variables declaration//GEN-END:variables
}
