/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author User
 */
public class ventas extends javax.swing.JFrame {

    /**
     * Creates new form ventas
     */
    public ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jdcFechaVenta = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxtCodCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtCodCliente1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlblImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaVenta = new javax.swing.JTable();
        jTxtISV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTxtRecargo = new javax.swing.JTextField();
        jTxtISV1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTxtISV2 = new javax.swing.JTextField();
        jTxtUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnListaFacturas = new javax.swing.JButton();
        jbtnListaFacturas1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTxtCodCliente2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTxtCodCliente3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTxtCodCliente4 = new javax.swing.JTextField();
        jbtnListaFacturas2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1100, 680));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 680));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel5.setLayout(null);
        jPanel5.add(jdcFechaVenta);
        jdcFechaVenta.setBounds(140, 40, 230, 30);

        jLabel12.setText("FECHA");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 40, 60, 20);

        jLabel11.setText("CÓDIGO");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 90, 110, 20);
        jPanel5.add(jTxtCodCliente);
        jTxtCodCliente.setBounds(140, 150, 230, 30);

        jLabel13.setText("CLIENTE");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(20, 160, 90, 20);
        jPanel5.add(jTxtCodCliente1);
        jTxtCodCliente1.setBounds(140, 90, 230, 30);

        jPanel2.setBackground(new java.awt.Color(237, 120, 74));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO DE VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblImagen)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
            .addComponent(jlblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "DETALLE DE VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel4.setLayout(null);

        jTablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "ID LIBRO", "LIBRO", "PRECIO", "CANTIDAD", "SUBTOTAL", "ISV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablaVenta);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 30, 590, 380);

        jTxtISV.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtISV.setEnabled(false);
        jPanel4.add(jTxtISV);
        jTxtISV.setBounds(470, 540, 140, 30);

        jLabel16.setText("ISV");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(350, 460, 50, 20);

        jLabel17.setText("TOTAL");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(350, 550, 80, 20);

        jLabel22.setText("DESCUENTO");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(350, 420, 110, 20);

        jTxtRecargo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtRecargo.setEnabled(false);
        jTxtRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRecargoActionPerformed(evt);
            }
        });
        jPanel4.add(jTxtRecargo);
        jTxtRecargo.setBounds(470, 420, 140, 30);

        jTxtISV1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtISV1.setEnabled(false);
        jPanel4.add(jTxtISV1);
        jTxtISV1.setBounds(470, 460, 140, 30);

        jLabel18.setText("SUBTOTAL");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(350, 510, 80, 20);

        jTxtISV2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTxtISV2.setEnabled(false);
        jPanel4.add(jTxtISV2);
        jTxtISV2.setBounds(470, 500, 140, 30);

        jTxtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTxtUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTxtUsuario.setForeground(new java.awt.Color(237, 120, 74));
        jTxtUsuario.setText("AQUÍ IRÁ EL USUARIO QUE ESTÁ INGRESANDO");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("USUARIO: ");

        jbtnListaFacturas.setBackground(new java.awt.Color(237, 120, 74));
        jbtnListaFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnListaFacturas.setText("FACTURAR");
        jbtnListaFacturas.setToolTipText("");
        jbtnListaFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListaFacturasActionPerformed(evt);
            }
        });

        jbtnListaFacturas1.setBackground(new java.awt.Color(237, 120, 74));
        jbtnListaFacturas1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnListaFacturas1.setText("VER FACTURAS");
        jbtnListaFacturas1.setToolTipText("");
        jbtnListaFacturas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListaFacturas1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(71, 84, 130), 2, true), "PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(71, 84, 130))); // NOI18N
        jPanel6.setLayout(null);

        jLabel19.setText("CÓDIGO");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel6.add(jLabel19);
        jLabel19.setBounds(20, 60, 110, 20);
        jPanel6.add(jTxtCodCliente2);
        jTxtCodCliente2.setBounds(140, 170, 230, 30);

        jLabel20.setText("CANTIDAD");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(20, 180, 90, 20);
        jPanel6.add(jTxtCodCliente3);
        jTxtCodCliente3.setBounds(140, 60, 230, 30);

        jLabel21.setText("PRODUCTO");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(20, 110, 90, 20);
        jPanel6.add(jTxtCodCliente4);
        jTxtCodCliente4.setBounds(140, 110, 230, 30);

        jbtnListaFacturas2.setBackground(new java.awt.Color(237, 120, 74));
        jbtnListaFacturas2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnListaFacturas2.setText("Agregar");
        jbtnListaFacturas2.setToolTipText("");
        jbtnListaFacturas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListaFacturas2ActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnListaFacturas2);
        jbtnListaFacturas2.setBounds(80, 230, 247, 36);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtnListaFacturas1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jbtnListaFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnListaFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnListaFacturas1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtUsuario)
                            .addComponent(jLabel6))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnListaFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListaFacturasActionPerformed
//        ViewFacturas listaFacturas = new ViewFacturas();
//        Menu_Principal.jDesktopPane1.add(listaFacturas);
//        Dimension desktopSize = Menu_Principal.jDesktopPane1.getSize();
//        Dimension FrameSize = listaFacturas.getSize();
//        listaFacturas.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
//        listaFacturas.show();
    }//GEN-LAST:event_jbtnListaFacturasActionPerformed

    private void jTxtRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRecargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRecargoActionPerformed

    private void jbtnListaFacturas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListaFacturas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnListaFacturas1ActionPerformed

    private void jbtnListaFacturas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListaFacturas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnListaFacturas2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablaVenta;
    private javax.swing.JTextField jTxtCodCliente;
    private javax.swing.JTextField jTxtCodCliente1;
    private javax.swing.JTextField jTxtCodCliente2;
    private javax.swing.JTextField jTxtCodCliente3;
    private javax.swing.JTextField jTxtCodCliente4;
    private javax.swing.JTextField jTxtISV;
    private javax.swing.JTextField jTxtISV1;
    private javax.swing.JTextField jTxtISV2;
    private javax.swing.JTextField jTxtRecargo;
    private javax.swing.JLabel jTxtUsuario;
    private javax.swing.JButton jbtnListaFacturas;
    private javax.swing.JButton jbtnListaFacturas1;
    private javax.swing.JButton jbtnListaFacturas2;
    private com.toedter.calendar.JDateChooser jdcFechaVenta;
    private javax.swing.JLabel jlblImagen;
    // End of variables declaration//GEN-END:variables
}
