/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abarroteria;


/**
 *
 * @author everg
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        panelfondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelbarra = new javax.swing.JPanel();
        btnclientes = new javax.swing.JButton();
        btnproductos = new javax.swing.JButton();
        btnventas = new javax.swing.JButton();
        btncompras = new javax.swing.JButton();
        btnproveedore = new javax.swing.JButton();
        btninventario = new javax.swing.JButton();
        btnreportes = new javax.swing.JButton();
        btnayuda = new javax.swing.JButton();
        prueba = new javax.swing.JPanel();
        lbllogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 1300, 700));
        setSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelfondo.setBackground(new java.awt.Color(153, 204, 255));
        panelfondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tus productos al alcance de tus manos");
        panelfondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 1110, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Supermercado ABC");
        panelfondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 1110, -1));

        panelbarra.setBackground(new java.awt.Color(102, 102, 102));
        panelbarra.setForeground(new java.awt.Color(242, 242, 242));
        panelbarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclientes.setBackground(new java.awt.Color(102, 102, 102));
        btnclientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnclientes.setForeground(new java.awt.Color(242, 242, 242));
        btnclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientesicon.png"))); // NOI18N
        btnclientes.setText("Clientes");
        btnclientes.setBorderPainted(false);
        btnclientes.setInheritsPopupMenu(true);
        panelbarra.add(btnclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnproductos.setBackground(new java.awt.Color(102, 102, 102));
        btnproductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnproductos.setForeground(new java.awt.Color(242, 242, 242));
        btnproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productoicon.png"))); // NOI18N
        btnproductos.setText("Productos");
        btnproductos.setBorderPainted(false);
        panelbarra.add(btnproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        btnventas.setBackground(new java.awt.Color(102, 102, 102));
        btnventas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnventas.setForeground(new java.awt.Color(242, 242, 242));
        btnventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventasicon.png"))); // NOI18N
        btnventas.setText("Ventas");
        btnventas.setBorderPainted(false);
        panelbarra.add(btnventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        btncompras.setBackground(new java.awt.Color(102, 102, 102));
        btncompras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncompras.setForeground(new java.awt.Color(242, 242, 242));
        btncompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comprasicon.png"))); // NOI18N
        btncompras.setText("Compras");
        btncompras.setActionCommand("Compras");
        btncompras.setBorderPainted(false);
        panelbarra.add(btncompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        btnproveedore.setBackground(new java.awt.Color(102, 102, 102));
        btnproveedore.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnproveedore.setForeground(new java.awt.Color(242, 242, 242));
        btnproveedore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedoricon.png"))); // NOI18N
        btnproveedore.setText("Proveedores");
        btnproveedore.setBorderPainted(false);
        panelbarra.add(btnproveedore, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        btninventario.setBackground(new java.awt.Color(102, 102, 102));
        btninventario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btninventario.setForeground(new java.awt.Color(242, 242, 242));
        btninventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventarioicon.png"))); // NOI18N
        btninventario.setText("Inventario");
        btninventario.setBorderPainted(false);
        panelbarra.add(btninventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        btnreportes.setBackground(new java.awt.Color(102, 102, 102));
        btnreportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreportes.setForeground(new java.awt.Color(242, 242, 242));
        btnreportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporticon.png"))); // NOI18N
        btnreportes.setText("Reportes");
        btnreportes.setBorderPainted(false);
        panelbarra.add(btnreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        btnayuda.setBackground(new java.awt.Color(102, 102, 102));
        btnayuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnayuda.setForeground(new java.awt.Color(242, 242, 242));
        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayudaicon.png"))); // NOI18N
        btnayuda.setText("Ayuda");
        btnayuda.setBorderPainted(false);
        panelbarra.add(btnayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        panelfondo.add(panelbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 1110, 40));

        javax.swing.GroupLayout pruebaLayout = new javax.swing.GroupLayout(prueba);
        prueba.setLayout(pruebaLayout);
        pruebaLayout.setHorizontalGroup(
            pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        pruebaLayout.setVerticalGroup(
            pruebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        panelfondo.add(prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1260, 490));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/supermercado_ABC_sinfondo.png"))); // NOI18N
        lbllogo.setInheritsPopupMenu(false);
        panelfondo.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        contentPane.add(panelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        getContentPane().add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    Principal frame = new Principal();

                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btncompras;
    private javax.swing.JButton btninventario;
    private javax.swing.JButton btnproductos;
    private javax.swing.JButton btnproveedore;
    private javax.swing.JButton btnreportes;
    private javax.swing.JButton btnventas;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbllogo;
    javax.swing.JPanel panelbarra;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JPanel prueba;
    // End of variables declaration//GEN-END:variables

}
