/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectog4;

import Conexion.ConexionBD;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sonia Elizabeth
 */
public class Login extends javax.swing.JFrame {
    String usuario, sentenciaSQL, cod="";
    Connection con = null;
    ConexionBD connec;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        jbtnOjoAbierto.setVisible(false);
    }
    
    public static void tamanioImg(JLabel imagen, String ruta) {
        ImageIcon img = new ImageIcon(ruta);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_DEFAULT));
        imagen.setIcon(icono);
    }
    
     public void conectarBD() {
        connec = new ConexionBD("openfirekafz");
        con = connec.getConexion();
    }
     
     public void limpiar(){
         txtUsername.setText(null);
         jpfPassword.setText(null);
         txtUsername.requestFocus();
     }
    
    public void validarCredenciales() {
    String username = txtUsername.getText();
    String password = new String(jpfPassword.getPassword());
    
     if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Los campos de usuario y contraseña son obligatorios", "Error de ingreso", JOptionPane.ERROR_MESSAGE);
        return;
    }
     else{
        sentenciaSQL = "SELECT * FROM usuario WHERE user = ? AND password = ? AND estadoUsuario=1";
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            connec = new ConexionBD("openfirekafz");
            con = connec.getConexion();
            ps = con.prepareStatement(sentenciaSQL);
            ps.setString(1, username);
            ps.setString(2, password);
            rs = ps.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "¡Bienvenido al Sistema " + username + ". ", "Logueo correcto", JOptionPane.INFORMATION_MESSAGE);

                classPrin.idUsuario =rs.getInt("idUsuario");
                classPrin.usuario = rs.getString("user");
                
                Menu_Principal menu = new Menu_Principal();
                menu.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario/Contraseña incorrecta. Intente de nuevo.", "Logueo incorrecto", JOptionPane.ERROR_MESSAGE);
                limpiar();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botLogin = new javax.swing.JButton();
        botSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnOjoAbierto = new javax.swing.JButton();
        jbtnOjoCerrado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jpfPassword = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("LOGIN");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(460, 160, 80, 40);

        botLogin.setBackground(new java.awt.Color(204, 153, 255));
        botLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botLogin.setForeground(new java.awt.Color(61, 74, 121));
        botLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (3).png"))); // NOI18N
        botLogin.setText("INGRESAR");
        botLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(61, 74, 121), 1, true));
        botLogin.setContentAreaFilled(false);
        botLogin.setFocusable(false);
        botLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario (2).png"))); // NOI18N
        botLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLoginActionPerformed(evt);
            }
        });
        jPanel2.add(botLogin);
        botLogin.setBounds(430, 350, 150, 30);

        botSalir.setBackground(new java.awt.Color(255, 255, 255));
        botSalir.setBorder(null);
        botSalir.setBorderPainted(false);
        botSalir.setContentAreaFilled(false);
        jPanel2.add(botSalir);
        botSalir.setBounds(0, 0, 20, 30);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 30, 0, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/test_account_96px.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(450, 50, 90, 110);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_32px.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(635, 0, 50, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/08- Logo The Book House.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 40, 130, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Libros3.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-80, -20, 400, 480);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 480);

        jbtnOjoAbierto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OjoAbierto.png"))); // NOI18N
        jbtnOjoAbierto.setBorderPainted(false);
        jbtnOjoAbierto.setContentAreaFilled(false);
        jbtnOjoAbierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOjoAbiertoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnOjoAbierto);
        jbtnOjoAbierto.setBounds(630, 280, 40, 40);

        jbtnOjoCerrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OjoCerrado.png"))); // NOI18N
        jbtnOjoCerrado.setBorderPainted(false);
        jbtnOjoCerrado.setContentAreaFilled(false);
        jbtnOjoCerrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOjoCerradoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnOjoCerrado);
        jbtnOjoCerrado.setBounds(630, 280, 40, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel3.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/password_24px.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 10, 30, 30);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(50, 40, 200, 10);

        jpfPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jpfPassword.setBorder(null);
        jPanel3.add(jpfPassword);
        jpfPassword.setBounds(50, 10, 200, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(360, 270, 270, 50);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel4.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_24px.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 30, 30);

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtUsername.setBorder(null);
        jPanel4.add(txtUsername);
        txtUsername.setBounds(50, 10, 210, 30);
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(50, 40, 200, 10);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(360, 210, 270, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLoginActionPerformed
        validarCredenciales();
    }//GEN-LAST:event_botLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnOjoAbiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOjoAbiertoActionPerformed
        jbtnOjoAbierto.setVisible(false);
        jbtnOjoCerrado.setVisible(true);
        jpfPassword.setEchoChar ('•');
    }//GEN-LAST:event_jbtnOjoAbiertoActionPerformed

    private void jbtnOjoCerradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOjoCerradoActionPerformed
        jbtnOjoAbierto.setVisible(true);
        jbtnOjoCerrado.setVisible(false);
        jpfPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_jbtnOjoCerradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botLogin;
    private javax.swing.JButton botSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnOjoAbierto;
    private javax.swing.JButton jbtnOjoCerrado;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
